# -*- coding: utf-8 -*-
"""slide_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RaC3Ub2VV3jxR_X4HIdXD274JasKtAM
"""

import os
import pandas as pd
from pptx import Presentation
from pptx.enum.shapes import PP_PLACEHOLDER

def create_ppt_from_dataframe(df, template_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    order = ['excluded', 'permission', 'aigen']
    df['attribution_type'] = pd.Categorical(df['attribution_type'], categories=order, ordered=True)

    for resource_name, resource_group in df.groupby('resource_name'):
        prs = Presentation(template_path)
        reference_layout_map = {
            'excluded': prs.slides[2].slide_layout,
            'permission': prs.slides[3].slide_layout,
            'aigen': prs.slides[4].slide_layout
        }
        xml_slides = prs.slides._sldIdLst
        insert_index = 2

        for attribution_type, type_group in resource_group.groupby('attribution_type', observed=True):
            for row in type_group.itertuples(index=False):
                slide_layout = reference_layout_map.get(attribution_type, reference_layout_map['excluded'])
                new_slide = prs.slides.add_slide(slide_layout)
                slide_id = xml_slides[-1]
                xml_slides.remove(slide_id)
                xml_slides.insert(insert_index + 1 + len(xml_slides) - 1, slide_id)

                body_text = getattr(row, 'attribution_text', '')
                body_set = False
                for shape in new_slide.placeholders:
                    if shape.is_placeholder and shape.placeholder_format.type == PP_PLACEHOLDER.BODY and shape.placeholder_format.idx == 2:
                        shape.text = body_text
                        body_set = True
                        break
                if not body_set:
                    for shape in new_slide.placeholders:
                        if shape.is_placeholder and shape.placeholder_format.type == PP_PLACEHOLDER.BODY:
                            shape.text = body_text
                            body_set = True
                            break
                if not body_set:
                    left = prs.slide_width / 4
                    top = prs.slide_height / 4
                    width = prs.slide_width / 2
                    height = prs.slide_height / 4
                    textbox = new_slide.shapes.add_textbox(left, top, width, height)
                    textbox.text = body_text

        output_filename = f"{resource_name}_slates.pptx"
        output_path = os.path.join(output_dir, output_filename)
        prs.save(output_path)
        print(f"✅ Presentation saved: {output_path}")

def main():
    csv_path = input("Enter path to CSV file: ")
    template_path = input("Enter Google Drive template path: ")
    output_dir = input("Enter Google Drive output directory: ")

    df = pd.read_csv(csv_path)
    create_ppt_from_dataframe(df, template_path, output_dir)

if __name__ == "__main__":
    main()